# Generated by Django 5.0.7 on 2024-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_groups_remove_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
    ]
