# Generated by Django 5.0.7 on 2024-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_table3'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tg_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
