# Generated by Django 5.0.7 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_tg_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
