# Generated by Django 5.0.7 on 2024-07-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('accuracy', models.FloatField()),
                ('image', models.ImageField(upload_to='license_plates/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
