# Generated by Django 5.0.7 on 2024-07-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseplate',
            name='accuracy',
        ),
    ]
