# Generated by Django 5.0.7 on 2024-07-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0004_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseplate',
            name='accuracy',
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('PARKING', 'PARKING'), ('FINISHED', 'FINISHED')], default='UNDEFINED')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('vehicle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_service.vehicle')),
            ],
        ),
    ]
