# Generated by Django 5.0.7 on 2024-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0006_alter_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
