# Generated by Django 5.0.7 on 2024-07-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0007_alter_parkingsession_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
