# Generated by Django 5.0.7 on 2024-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0008_vehicle_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='end_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
