# Generated by Django 5.0.7 on 2024-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0009_alter_parkingsession_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
