# Generated by Django 5.0.7 on 2024-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0010_alter_parkingsession_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='parking_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
