# Generated by Django 5.0.7 on 2024-07-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0011_parkingsession_parking_duration'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
