# Generated by Django 5.0.7 on 2024-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0012_alter_parkingsession_vehicle_delete_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED')], default='UNDEFINED'),
        ),
    ]
