# Generated by Django 5.0.7 on 2024-07-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_service", "0013_alter_parkingsession_status"),
        ("vehicles", "0004_alter_vehicle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingsession",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehicle",
            ),
        ),
    ]
