# Generated by Django 5.0.7 on 2024-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_service", "0015_parkingsession_vehicle_plate_number"),
        ("vehicles", "0004_alter_vehicle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDEFINED", "UNDEFINED"),
                    ("ACTIVE", "ACTIVE"),
                    ("FINISHED", "FINISHED"),
                ],
                default="UNDEFINED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spot_number", models.CharField(max_length=10, unique=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parkingsession",
            name="parking_spot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parking_service.parkingspot",
            ),
        ),
    ]
