# Generated by Django 5.0.7 on 2024-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_service", "0016_alter_parkingsession_status_parkingspot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="spot_number",
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
