# Generated by Django 5.0.7 on 2024-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_service", "0017_remove_parkingspot_spot_number_alter_parkingspot_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parkingspot",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="parkingsession",
            name="vehicle_plate_number",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
