# Generated by Django 5.0.7 on 2024-07-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_service", "0018_alter_parkingspot_options_and_more"),
        ("parking_service", "0019_alter_parkingsession_vehicle_plate_number"),
    ]

    operations = []
