# Generated by Django 5.0.7 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_service", "0020_merge_20240729_0725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingsession",
            name="vehicle_plate_number",
            field=models.CharField(max_length=10),
        ),
    ]
