# Generated by Django 5.0.7 on 2024-07-24 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='start_date',
            field=models.DateField(),
        ),
    ]
