# Generated by Django 5.0.7 on 2024-07-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_tariff_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='parking_session_id',
            new_name='parking_session_pk',
        ),
    ]
