# Generated by Django 5.0.7 on 2024-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_rename_parking_session_id_payment_parking_session_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="current_tariff",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
