# Generated by Django 5.0.7 on 2024-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_payment_current_tariff"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="full_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
