# Generated by Django 5.0.7 on 2024-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_payment_full_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="full_hours",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
