# Generated by Django 5.0.7 on 2024-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
