# Generated by Django 5.0.7 on 2024-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("debit", "Debit")],
                default="DEBIT",
                max_length=10,
            ),
        ),
    ]
