# Generated by Django 5.0.7 on 2024-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_payment_user_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
