# Generated by Django 5.0.7 on 2024-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_payment_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("CONFIRMED", "CONFIRMED"), ("UNCONFIRMED", "UNCONFIRMED")],
                default="UNCONFIRMED",
                max_length=12,
            ),
        ),
    ]
