# Generated by Django 5.0.7 on 2024-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('BLOCKED', 'BLOCKED')], default='ACTIVE'),
        ),
    ]
